name: BuildandTest

on:
#  schedule:
#    - cron: "29 */6 * * *"
  push:

jobs:
  build_source:

    name: Builder
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Build  and Test
        run: python arugment.ipynb
